language: node_js

node_js:
  - "stable"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - npm install

script:
  - npm run test