language: node_js

node_js:
  - "stable"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

before_script:
  - yarn install

script:
  - yarn run test