const states = [
  { id: 1, text: 'Aguascalientes', value: 'aguascalientes' },
  { id: 2, text: 'Baja California', value: 'baja' },
  { id: 3, text: 'Baja California Sur', value: 'baja-sur' },
  { id: 4, text: 'Campeche', value: 'campeche' },
  { id: 5, text: 'Coahuila de Zaragoza', value: 'coahuila' },
  { id: 6, text: 'Colima', value: 'colima' },
  { id: 7, text: 'Chiapas', value: 'chiapas' },
  { id: 8, text: 'Chihuahua', value: 'chihuahua' },
  { id: 9, text: 'Ciudad de México', value: 'cdmx' },
  { id: 10, text: 'Durango', value: 'durango' },
  { id: 11, text: 'Guanajuato', value: 'guanajuato' },
  { id: 12, text: 'Guerrero', value: 'guerrero' },
  { id: 13, text: 'Hidalgo', value: 'hidalgo' },
  { id: 14, text: 'Jalisco', value: 'jalisco' },
  { id: 15, text: 'México', value: 'mexico' },
  { id: 16, text: 'Michoacán de Ocampo', value: 'michoacan' },
  { id: 17, text: 'Morelos', value: 'morelos' },
  { id: 18, text: 'Nayarit', value: 'nayarit' },
  { id: 19, text: 'Nuevo León', value: 'nuevo-leon' },
  { id: 20, text: 'Oaxaca', value: 'oaxaca' },
  { id: 21, text: 'Puebla', value: 'puebla' },
  { id: 22, text: 'Querétaro', value: 'queretaro' },
  { id: 23, text: 'Quintana Roo', value: 'quintana-roo' },
  { id: 24, text: 'San Luis Potosí', value: 'san-luis' },
  { id: 25, text: 'Sinaloa', value: 'sinaloa' },
  { id: 26, text: 'Sonora', value: 'sonora' },
  { id: 27, text: 'Tabasco', value: 'tabasco' },
  { id: 28, text: 'Tamaulipas', value: 'tamaulipas' },
  { id: 29, text: 'Tlaxcala', value: 'tlaxcala' },
  { id: 30, text: 'Veracruz de Ignacio de la Llave', value: 'veracruz' },
  { id: 31, text: 'Yucatán', value: 'yucatan' },
  { id: 32, text: 'Zacatecas', value: 'zacatecas' },
];

export default states;
