apiVersion: v1
kind: Pod
metadata:
  name: villafeet-app
  labels:
    zone: dev
    version: v1
spec:
  containers:
  - name: villafeet-app
    image: jaycorpstudios/villafeet:fe-latest
    ports:
    - containerPort: 80
    imagePullPolicy: Never