
//LOGIN
export const PROCESS_LOGIN = 'PROCESS_LOGIN';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const PROCESS_LOGOUT = 'PROCESS_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';