
//LOGIN
export const PROCESS_LOGIN = 'PROCESS_LOGIN';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const PROCESS_LOGOUT = 'PROCESS_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//PATIENT
export const ADD_PATIENT = 'ADD_PATIENT';
export const PATIENT_RECORD_IN_PROGRESS = 'PATIENT_RECORD_IN_PROGRESS';
export const PATIENT_RECORD_SUCCESS = 'PATIENT_RECORD_SUCCESS';
export const PATIENT_RECORD_FAILED = 'PATIENT_RECORD_FAILED';
export const PATIENT_RECORD_RESTORE = 'PATIENT_RECORD_RESTORE';