
// LOGIN
export const PROCESS_LOGIN = 'PROCESS_LOGIN';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const PROCESS_LOGOUT = 'PROCESS_LOGOUT';

// USER
export const USER_GET = 'USER_GET';
export const USER_IN_PROGRESS = 'USER_IN_PROGRESS';
export const USER_SUCCESS = 'USER_SUCCESS';

// PATIENT
export const ADD_PATIENT = 'ADD_PATIENT';
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const SET_PATIENT = 'SET_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const SET_NEW_PATIENT = 'SET_NEW_PATIENT';
export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const SET_PATIENTS = 'SET_PATIENTS';
export const FETCH_KEY_ADD_PATIENT = 'FETCH_KEY_ADD_PATIENT';
export const FETCH_KEY_GET_PATIENT = 'FETCH_KEY_GET_PATIENT';
export const FETCH_KEY_LIST_PATIENTS = 'FETCH_KEY_LIST_PATIENTS';

// FETCH (for Fetch High Order Reducer)
export const FETCH_IN_PROGRESS = 'FETCH_IN_PROGRESS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_RESET = 'FETCH_RESET';
