apiVersion: v1
kind: ReplicationController
metadata:
  name: rest-rc
  labels:
    zone: dev
    version: v1
spec:
  replicas: 1
  selector:
    app: villafeet-rest
  template:
    metadata:
      labels:
        app: villafeet-rest
    spec:
      containers:
      - name: villafeet-rest
        image: jaycorpstudios/villafeet:be-latest
        ports:
        - containerPort: 4040
        imagePullPolicy: Never