apiVersion: v1
kind: ReplicationController
metadata:
  name: villafeet-rc
  labels:
    zone: dev
    version: v1
spec:
  replicas: 3
  selector:
    app: villafeet-app
  template:
    metadata:
      labels:
        app: villafeet-app
    spec:
      containers:
      - name: villafeet-app
        image: jaycorpstudios/villafeet:fe-latest
        ports:
        - containerPort: 80
        imagePullPolicy: Never